# Generated by Django 5.2.6 on 2025-09-21 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registered_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
