# Generated by Django 5.2.6 on 2025-09-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_schedule_registered_users_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered_users',
        ),
    ]
