# Generated by Django 5.2.6 on 2025-09-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_registered_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='name',
        ),
    ]
